// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/bfc-open-rpc/spec/openrpc.json
 */

import type { GetObjectParams } from '../../../client/index.js';
import type { UseSuiClientQueryOptions } from '../useSuiClientQuery.js';
import { useSuiClientQuery } from '../useSuiClientQuery.js';

export function useObject(
	params: GetObjectParams,
	options?: UseSuiClientQueryOptions<'getObject'>,
) {
	return useSuiClientQuery(
		{
			method: 'getObject',
			params,
		},
		options,
	);
}
