// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/bfc-open-rpc/spec/openrpc.json
 */

import type { ResolveNameServiceAddressParams } from '../../../client/index.js';
import type { UseSuiClientQueryOptions } from '../useSuiClientQuery.js';
import { useSuiClientQuery } from '../useSuiClientQuery.js';

export function useResolveNameServiceAddress(
	params: ResolveNameServiceAddressParams,
	options?: UseSuiClientQueryOptions<'resolveNameServiceAddress'>,
) {
	return useSuiClientQuery(
		{
			method: 'resolveNameServiceAddress',
			params,
		},
		options,
	);
}
